### ISSUE TITLE
Error when running from command-line

### ISSUE THREAD

**Issue by ErikSchierboom** [cdnjs/cdnjs-importer#4]
I have installed the module globally and then try to run it as follows:

`cdnjs-importer -c /Users/erikschierboom/Programming/cdnjs git@github.com:ErikSchierboom/knockout-pre-rendered.git`

I then get the following error:

```
/usr/local/lib/node_modules/cdnjs-importer/lib/index.js:100
 in autoupdate process (default: `[{ basePath: lib.dir , files: ["**/*"] }]`).
                                                                     ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cdnjs-importer/bin/cdnjs-importer:4:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by IonicaBizau** [comment]
Whoups, probably after merging #3.

I'm on it.

**Comment by IonicaBizau** [comment]
I committed a fix. Please update the tool using `npm i -g cdnjs-importer@latest`.

**Comment by ErikSchierboom** [comment]
Thanks for the quick fix!

**Comment by IonicaBizau** [comment]
I thank you for reporting this issue! :cake:
